### ISSUE TITLE
Confused by PulseTimer terminology

### ISSUE THREAD

**Issue by gtjoseph** [BroadwellConsultingInc/SerialWombatArdLib#2]
From the docs:
```
uint16_t SerialWombatPulseTimer::readHighCounts()	
Retreives the most recent Counts in the configured units for the most recent high pulse.

Returns
Counts in mS or uS depending on configuration.
```
I'm really confused by this.  You don't measure "counts" in time units.  You can measure them _over_ a specific length of time but "counts in mS or uS"?  I don't get it.  

Ideally, I'm trying to retrieve the number of debounced pulses over a period of time and have the count reset on read.    The DebouncedInput though seems geared for button presses and not say a reed switch.   Where the pulse rate is less than the sample rate, I can just check for _any_ transitions since the last sample and count that as a 1.   For higher pulse rates, say 100Hz at about a 15% duty cycle, it's harder to figure out what's a legitimate pulse and what's noise caused by the switch.    If the pulse rate is variable, as it is in my case, it's hard to tell the DebouncedInput the length of a "good" pulse.

Any thoughts on this?

**Comment by BroadwellConsultingInc** [comment]
In the future, please ask support / implementation questions on the appropriate YouTube video (best case because that gives the most visibility to help other users) or send to help@serialWombat.com rather than opening an issue against the library.  

The Pulse Timer function is designed to measure how long a signal is high or low  The "High Counts" is simply a time delta in uS or mS of how much time elapsed between the last low to high transition and high to low transition.  It doesn't do any debouncing.

The Debounced input is going to be your best bet in general for removing noise, but you do need to be able to set a minimum amount of time, and you're right that 100Hz with a 15% duty cycle isn't practical at a 1kHz sample rate.  

Is it practical to put an analog filter such as an RC filter on the switch output to eliminate noise, then use the pulse timer function on the filtered input?

**Comment by gtjoseph** [comment]
> In the future, please ask support / implementation questions on the appropriate YouTube video (best case because that gives the most visibility to help other users) or send to [help@serialWombat.com](mailto:help@serialWombat.com) rather than opening an issue against the library.

Oops, sorry about that.  It wasn't obvious where to post issues.   You know you can disable issues under repository settings right? :)  

> The Pulse Timer function is designed to measure how long a signal is high or low The "High Counts" is simply a time delta in uS or mS of how much time elapsed between the last low to high transition and high to low transition. It doesn't do any debouncing.

Ah, now that makes sense.  It was the "Counts" that was throwing me off.

> The Debounced input is going to be your best bet in general for removing noise, but you do need to be able to set a minimum amount of time, and you're right that 100Hz with a 15% duty cycle isn't practical at a 1kHz sample rate.

As always happens, I woke up in the middle of the night and thought...  "I know what the fastest pulse rate is going to be and it's probably much slower than the bounce noise.  I should be able to set the minimum time from that.".  I'll be testing with my logic analyzer today. :)

> 
> Is it practical to put an analog filter such as an RC filter on the switch output to eliminate noise, then use the pulse timer function on the filtered input?

That's certainly a possibility.  

Thanks for your help and the product!  I've already used the 8 4Bs I had and will be ordering more shortly.
